version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MODEL_NAME=${MODEL_NAME}
      - TEMPERATURE=${TEMPERATURE}
      - TOP_P=${TOP_P}
      - TOP_K=${TOP_K}
      - MAX_OUTPUT_TOKENS=${MAX_OUTPUT_TOKENS}
      - SYSTEM_INSTRUCTION=${SYSTEM_INSTRUCTION}
    restart: unless-stopped